spring:
  # db 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dailytalk_admin_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '!hj246810!'
    hikari:
      connection-test-query: SELECT 1
    jpa:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      format_sql: true #To beautify or pretty print the SQL
      show_sql: true #show sql
      generate-ddl: true
      hibernate:
        ddl-auto: create
  # OAuth 로그인
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: fc3e1da6721701b7c3905c5ab7e72751
            client-secret: lbR1bT2LhHt4j1vL2hLlvh1HzVg9vK9X
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST #카카오는 필수 파라미터를 POST로 요청해야됌!

          naver:
            client-id: jujS2Om886bui7xAwRmV
            client-secret: x26dutLdtm
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response